name: raconteur
channels:
  - pytorch-nightly
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - astroid=2.14.2=py311h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py311hbed6279_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311h06a4308_0
  - colorama=0.4.6=py311h06a4308_0
  - cryptography=41.0.3=py311hdda0065_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.52=0
  - cuda-runtime=12.1.0=0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.7=py311h06a4308_0
  - docstring-to-markdown=0.11=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h20bf706_0
  - flake8=6.0.0=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipython=8.15.0=py311h06a4308_0
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py311h06a4308_1
  - jinja2=3.1.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.6.0=py311h5eee18b_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.0.34=0
  - libcurand=10.3.4.52=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py311_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.1=py311h06a4308_0
  - pandas=2.1.1=py311ha02d727_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py311h3fd9d12_2
  - pip=23.3=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - pluggy=1.0.0=py311h06a4308_1
  - prompt-toolkit=3.0.36=py311h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.10.0=py311h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=py311h06a4308_0
  - pyflakes=3.0.1=py311h06a4308_0
  - pygments=2.15.1=py311h06a4308_1
  - pylint=2.16.2=py311h06a4308_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.7.2=py311h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytoolconfig=1.2.5=py311h06a4308_1
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py311h06a4308_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - rope=1.7.0=py311h06a4308_0
  - scipy=1.11.3=py311h08b1b3b_0
  - setuptools=68.0.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - traitlets=5.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - ujson=5.4.0=py311h6a678d5_0
  - urllib3=1.26.18=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - whatthepatch=1.0.2=py311h06a4308_0
  - wheel=0.41.2=py311h06a4308_0
  - wrapt=1.14.1=py311h5eee18b_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiofiles==24.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - attrs==25.1.0
      - audioread==3.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - blinker==1.9.0
      - blis==0.7.11
      - brotli==1.2.0
      - catalogue==2.0.10
      - cfgv==3.5.0
      - chatterbox-tts==0.1.6
      - cloudpathlib==0.21.0
      - confection==0.1.5
      - conformer==0.3.2
      - csvw==3.5.1
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - cymem==2.0.11
      - dawg-python==0.7.2
      - deprecated==1.3.1
      - diffusers==0.29.0
      - distlib==0.4.0
      - dlinfo==2.0.0
      - docopt==0.6.2
      - einops==0.8.1
      - en-core-web-sm==3.8.0
      - espeakng-loader==0.2.4
      - fastapi==0.128.0
      - ffmpy==1.0.0
      - filelock==3.20.1
      - flask==3.1.0
      - fsspec==2025.2.0
      - future==1.0.0
      - gradio==5.44.1
      - gradio-client==1.12.1
      - groovy==0.1.2
      - h11==0.14.0
      - hf-xet==1.2.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - identify==2.6.15
      - importlib-metadata==8.7.1
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jaconv==0.4.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kokoro==0.8.4
      - langcodes==3.5.0
      - language-data==1.3.0
      - language-tags==1.2.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - loguru==0.7.3
      - lxml==6.0.2
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - misaki==0.8.4
      - ml-dtypes==0.5.4
      - msgpack==1.1.2
      - murmurhash==1.0.12
      - music-tag==0.4.3
      - mutagen==1.47.0
      - nodeenv==1.10.0
      - num2words==0.5.13
      - numba==0.63.1
      - numpy==1.25.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - onnx==1.20.0
      - orjson==3.11.5
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - phonemizer-fork==3.3.2
      - pooch==1.8.2
      - pre-commit==4.5.1
      - preshed==3.0.9
      - protobuf==6.33.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pykakasi==2.3.0
      - pyloudnorm==0.1.1
      - pymorphy2==0.9.1
      - pymorphy2-dicts-ru==2.4.417127.4579844
      - pyparsing==3.2.1
      - python-multipart==0.0.21
      - python-telegram-bot==21.11.1
      - rdflib==7.1.3
      - referencing==0.36.2
      - regex==2024.11.6
      - resemble-perth==1.0.1
      - rfc3986==1.5.0
      - rich==13.9.4
      - rpds-py==0.23.1
      - ruff==0.14.10
      - russian-text-stresser==0.1.1
      - s3tokenizer==0.3.0
      - safehttpx==0.1.7
      - safetensors==0.5.3
      - scikit-learn==1.8.0
      - segments==2.3.0
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - smart-open==6.4.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - soxr==1.0.0
      - spacy==3.6.1
      - spacy-curated-transformers==0.3.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-pkuseg==1.0.1
      - srsly==2.5.1
      - starlette==0.50.0
      - stressed-cyrillic-tools==0.1.15
      - sympy==1.14.0
      - thinc==8.1.12
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - tomlkit==0.13.3
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchcodec==0.9.1
      - torchvision==0.24.1
      - transformers==4.46.3
      - transliterate==1.10.2
      - triton==3.5.1
      - typer==0.9.4
      - typing-extensions==4.12.2
      - uritemplate==4.1.1
      - uvicorn==0.40.0
      - virtualenv==20.35.4
      - wasabi==1.1.3
      - weasel==0.4.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - zipp==3.23.0
prefix: /home/zeio/miniconda3/envs/raconteur
